project:
  type: website
  output-dir: "docs/"

website:
  title: "Demonstração de Infográficos"
  navbar:
    left:
      - href: index.qmd
        text: CGINF
      - about.qmd

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true

editor: visual

lang: pt
